set(_CATKIN_CURRENT_PACKAGE "hexaplus_tutorial")
set(hexaplus_tutorial_MAINTAINER "Emanoel Koslosky <ekosky@gmail.com>")
set(hexaplus_tutorial_DEPRECATED "")
set(hexaplus_tutorial_VERSION "0.0.1")
set(hexaplus_tutorial_BUILD_DEPENDS "roscpp" "std_msgs")
set(hexaplus_tutorial_RUN_DEPENDS "roscpp" "std_msgs")
set(hexaplus_tutorial_BUILDTOOL_DEPENDS "catkin")